apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
#Deployment specifications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
#Pod specifications
    spec:
      containers:
      -  name: nginx
         image: nginx:latest
         ports:
         -  containerPort: 80
